# Generated by Django 5.0.7 on 2024-07-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_listing',
            old_name='square_foootage',
            new_name='square_footage',
        ),
    ]
