# Generated by Django 5.0.7 on 2024-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_square_foootage_properties_listing_square_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
