# Generated by Django 5.0.7 on 2024-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_properties_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='google_map',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties_listing',
            name='video',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
