# Generated by Django 5.0.7 on 2024-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_properties_listing_google_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties_listing',
            name='video',
        ),
        migrations.AddField(
            model_name='properties_listing',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
