# Generated by Django 5.0.7 on 2024-08-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_properties_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='location',
            field=models.CharField(choices=[('Kano', 'Kano'), ('Abuja', 'Abuja')], max_length=50),
        ),
    ]
