# Generated by Django 5.0.7 on 2024-07-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_remove_properties_listing_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
