# Generated by Django 5.0.7 on 2024-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_properties_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
