# Generated by Django 5.0.7 on 2024-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_properties_listing_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
