# Generated by Django 5.0.7 on 2024-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_properties_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='parking_space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
