# Generated by Django 5.0.7 on 2024-07-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_properties_listing_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_listing',
            old_name='rooms',
            new_name='parking_space',
        ),
    ]
