# Generated by Django 5.0.7 on 2024-07-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_rename_rooms_properties_listing_parking_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_listing',
            old_name='square_footage',
            new_name='sqm',
        ),
    ]
