# Generated by Django 5.1.6 on 2025-02-18 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Properties_Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("parking_space", models.IntegerField(blank=True, null=True)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("size", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("certificate_num", models.CharField(max_length=64)),
                ("reference_num", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=500)),
                ("google_map", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("For Rent", "For Rent"), ("For Sale", "For Sale")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Flat/Apartment", "Flat/Apartment"),
                            ("House", "House"),
                            ("Plot/Land", "Plot/Land"),
                            ("Commercial", "Commercial"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("Kano", "Kano"), ("Abuja", "Abuja")], max_length=50
                    ),
                ),
                (
                    "saved_by_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="saved_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="public.properties_listing",
                    ),
                ),
            ],
        ),
    ]
