# Generated by Django 5.0.7 on 2025-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='certificate_num',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='reference_num',
            field=models.CharField(default='', max_length=255),
        ),
    ]
