# Generated by Django 5.0.7 on 2024-09-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_listing',
            old_name='sqm',
            new_name='size',
        ),
    ]
