# Generated by Django 5.1.6 on 2025-02-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties_listing",
            name="certificate_num",
        ),
    ]
