# Generated by Django 5.1.6 on 2025-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_remove_properties_listing_certificate_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties_listing",
            name="certificate_num",
            field=models.CharField(default="", max_length=255),
        ),
    ]
