# Generated by Django 5.0.7 on 2024-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_sqm_properties_listing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='certificate_num',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties_listing',
            name='reference_num',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
