# Generated by Django 5.0.7 on 2024-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_properties_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='category',
            field=models.CharField(choices=[('flat', 'Flat'), ('apartment', 'Apartment'), ('house', 'House'), ('plot', 'Plot/Land'), ('commercial', 'Commercial')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='location',
            field=models.CharField(choices=[('kano', 'Kano'), ('abuja', 'Abuja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='status',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10),
        ),
    ]
