# Generated by Django 5.0.7 on 2024-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_properties_listing_certificate_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='certificate_num',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='reference_num',
            field=models.CharField(max_length=64),
        ),
    ]
