# Generated by Django 5.0.7 on 2024-08-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_properties_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='category',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Apartment', 'Apartment'), ('House', 'House'), ('Plot/Land', 'Plot/Land'), ('Commercial', 'Commercial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='properties_listing',
            name='status',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=10),
        ),
    ]
