# Generated by Django 5.1.6 on 2025-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_properties_listing_certificate_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties_listing",
            name="reference_num",
            field=models.CharField(default="", max_length=255),
        ),
    ]
