# Generated by Django 5.0.7 on 2024-08-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_properties_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='category',
            field=models.CharField(choices=[('Flat/Apartment', 'Flat/Apartment'), ('House', 'House'), ('Plot/Land', 'Plot/Land'), ('Commercial', 'Commercial')], max_length=50),
        ),
    ]
