# Generated by Django 5.0.7 on 2024-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='second_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
