# Generated by Django 5.0.7 on 2024-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_properties_listing_second_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_listing',
            name='second_image_url',
            field=models.URLField(auto_created=True, blank=True, null=True),
        ),
    ]
