# Generated by Django 5.0.7 on 2024-09-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_properties_listing_second_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties_listing',
            name='second_image_url',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public.properties_listing'),
        ),
    ]
