# Generated by Django 5.0.7 on 2024-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_properties_listing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
