# Generated by Django 5.0.7 on 2024-08-29 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_properties_listing_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_listing',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
